---
- hosts: all
  tasks:
  - name: Install MySQL
    become: yes
    apt:
      name: mysql-server
      state: present
  - name: Start MySQL service
    become: yes
    service:
      name: mysql
      state: started
      enabled: true
